package spring.application.tree.web.webscoket.models;

public enum WebSocketEvent {
    ORDER_CREATED, ORDER_UPDATED, ORDER_DELETED,
    PRODUCT_CREATED, PRODUCT_UPDATED, PRODUCT_DELETED, PRODUCT_ORDERED, PRODUCT_DISORDERED,
    CUSTOMER_CREATED, CUSTOMER_UPDATED, CUSTOMER_DELETED,
    WORKER_CREATED, WORKER_UPDATED, WORKER_DELETED,
    ORDER_ASSIGNED, ORDER_REMOVED,
}
